# Generated by Django 4.1.5 on 2023-02-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default='writer', max_length=255),
            preserve_default=False,
        ),
    ]
