# Generated by Django 4.1.5 on 2023-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_readers_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'So So'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], null=True),
        ),
    ]
