# Generated by Django 4.1.5 on 2023-05-10 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_commentbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbook',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='commentbook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

        migrations.RemoveField(
            model_name='book',
            name='readers',
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='commentbook',
            name='book',
        ),


        migrations.AddField(
            model_name='commentbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.book'),
        ),
        migrations.RemoveField(
            model_name='commentbook',
            name='comment'
        ),
        migrations.AddField(
            model_name='commentbook',
            name='comment',
            field=models.TextField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='UserBookRelation',
        ),
    ]
