# Generated by Django 4.1.5 on 2023-05-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_book_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentbook',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='commentbook',
            name='book',
        ),
        migrations.AddField(
            model_name='commentbook',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
    ]
