# Generated by Django 4.1.5 on 2023-05-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_user_commentbook_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentbook',
            old_name='book_id',
            new_name='book',
        ),
    ]
