# Generated by Django 4.1.5 on 2023-05-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_book_id_commentbook_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentbook',
            old_name='user_id',
            new_name='user',
        ),
    ]
