# Generated by Django 4.1.5 on 2023-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_book_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
