# Generated by Django 4.1.5 on 2023-06-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_book_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='like',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
