# Generated by Django 4.1.5 on 2023-06-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_book_likes_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='action',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
