# Generated by Django 4.1.5 on 2023-06-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_book_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='action',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
