# Generated by Django 4.1.5 on 2023-07-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='action',
        ),
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
